Fix wrong twist in odometry messages
FS-Driverless/Formula-Student-Driverless-Simulator pull request #284
Opened 2022-02-02 22:08 UTC by mateusz-lichota

As discussed in #283

2022-02-08 18:10 UTC, mateusz-lichota commented
@wouter-heerwegh care to take a look at the changes?

2022-02-08 18:26 UTC, wouter-heerwegh requested changes
Sorry, I didn't know you couldn't see my review.

2022-02-09 14:45 UTC, mateusz-lichota commented on ros2/src/fsds_ros2_bridge/src/airsim_ros_wrapper.cpp
> +    odom_enu_msg.twist.twist.angular.y = 0;
linear.z should definitely be 0, as the car won't move int the up/down direction. Same for angular.x and angular.y: for those to be meaningfully nonzero the car would have to roll over or jump of a ramp, both of which are not scenarios we expect, support or care about here. I agree with you that linear.y shouldn't always be set to zero, and I'll look into how we can achieve that.

2022-02-09 15:02 UTC, wouter-heerwegh commented on ros2/src/fsds_ros2_bridge/src/airsim_ros_wrapper.cpp
> +    odom_enu_msg.twist.twist.angular.y = 0;
The car will roll and pitch quite a lot, a lot more than our actual car. I agree that the measurement will most likely not be very useful, but I think it is still better to add these for completeness.

2022-07-14 17:11 UTC, mateusz-lichota commented
Hey @wouter-heerwegh, I've implemented the computation for sideways velocity using the yaw angle to compute it from map frame velocities. However, transforming the angular velocities is quite difficult, and I think is not necessary, because when the car rolls and pitches what matters to people is the actual roll and pitch, and very rarely the roll rate or pitch rate. I honestly can't think of any practical use for those values, but if any is found someone more experienced than me can write the appropriate transformation code.

2022-07-16 06:04 UTC, wouter-heerwegh approved these changes
LGTM, thank you very much!

2022-07-16 06:04 UTC, merged